### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by maelle** [darokun/rladies_iwd2018_tweets#2]
First and foremost, awesome post, thanks for doing that!

A few comments

* You can't get all tweets with `get_timeline`, there's a limit which I can't remember, but e.g. you can't get _my_ whole timeline like that :joy: 

* "Unsurprisingly, most tweets were posted on International Women’s Day!" <- they were all sent on IWD... somewhere on Earth. With timezones etc., the day lasts much more than 24h.

* I'd actually be against showing the most favourited but if you do say that at the beginning handles were used, after a while no longer (Kelly explains that in her post), and that the most liked might be the first ones (no of retweets/likes vs time?). The reason I'm against that is that the most "famous" R-Ladies might be in that set and the whole idea of that Twitter action was to not feature only the usual "stars" who already get a lot of exposure. So if you agree, I'd remove that entirely, or at least remove _my_ name 😜 

* There's a function to get someone's name from the ID cf e.g. https://github.com/lockedata/twitter_book_draw/blob/master/R/code.R#L7 With that you could actually "translate" all IDs from the table with the no. of tweets?

* Reg the htmlwidget check with @chucheria that it works 😁 

All in all, super interesting blog post, really well done! 👏

**Comment by darokun** [comment]
Thanks for your comments!

**Comment by darokun** [comment]
Add suggestions.
